### ISSUE TITLE
boost/boost-lib upgrade 1.80-1.81 breaks roscore/rosout

### ISSUE THREAD

**Issue by phansel** [ros-noetic-arch/ros-noetic-ros-core#2]
Upgrading boost and boost-libs to 1.81 on a ros-noetic-ros-core "built" on boost-1.80 seems to break roscore/rosout. Trying to track this dependency down now.

**Comment by acxz** [comment]
Can you post the error output and the corresponding method of reproducing it?

**Comment by phansel** [comment]
I'll close it for now. Reinstalling ros-noetic-ros-core after the update may have fixed it.

**Comment by acxz** [comment]
That will do the trick if the issue is what I think it is. Posting this comment just in case anyone else needs to see it: https://github.com/ros-noetic-arch/ros-noetic-desktop-full/issues/10#issuecomment-653168991
